
import { PrismaClient, UserRole, ListingType, ListingStatus, ApprovalStatus, ServiceProviderType, SubscriptionStatus, PackageBillingType, PackageTarget } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();
const SALT_ROUNDS = 10;
const DEFAULT_PASSWORD = 'Password123!';

const CITIES = [
  "Manama", "Riffa", "Muharraq", "Hamad Town", "Isa Town", 
  "Sitra", "Budaiya", "Jidhafs", "Hidd", "Zallaq"
];

const LUXURY_BRANDS = ["Rolls Royce", "Bentley", "Ferrari", "Lamborghini", "Aston Martin", "McLaren", "Bugatti", "Maserati", "Porsche", "Maybach"];
const CLASSIC_BRANDS = ["Ford Mustang", "Chevrolet Camaro", "Mercedes-Benz SL", "Volkswagen Beetle", "Dodge Charger", "Cadillac Eldorado", "Jaguar E-Type", "Pontiac GTO", "Chevrolet Corvette", "Mini Cooper"];

// Helper to get random item
function rnd<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

async function ensurePackageExists(user: any) {
  // Check if user has active subscription
  const sub = await prisma.subscription.findFirst({
    where: { userId: user.id, status: SubscriptionStatus.ACTIVE }
  });

  if (!sub) {
    // Create or find a default package
    const pkg = await prisma.package.upsert({
      where: { nameEn: 'Unlimited Seed Package' },
      create: {
        nameEn: 'Unlimited Seed Package',
        nameAr: 'باقة غير محدودة',
        price: 0,
        billingType: PackageBillingType.YEARLY,
        features: { listings: 999, stories: 999, featured: 999 },
        targetAudience: PackageTarget.ALL
      },
      update: {}
    });

    await prisma.subscription.create({
      data: {
        userId: user.id,
        packageId: pkg.id,
        startDate: new Date(),
        endDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
        status: SubscriptionStatus.ACTIVE,
        limits: pkg.features as any
      }
    });
  }
}

async function createStory(userId: string, type: 'IMAGE' | 'VIDEO' = 'IMAGE') {
  await prisma.story.create({
    data: {
      userId,
      mediaUrl: type === 'VIDEO' 
        ? 'https://res.cloudinary.com/demo/video/upload/v1/dog.mp4' 
        : `https://dummyimage.com/600x1200/${Math.floor(Math.random()*16777215).toString(16)}/fff&text=Story+${userId.substring(0,4)}`,
      mediaType: type,
      caption: 'Check out this update! 🚗✨',
      status: ApprovalStatus.APPROVED,
      expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000) // 24 hours
    }
  });
}

async function createListing(
  userId: string, 
  type: ListingType, 
  overrides: any = {}, 
  listingTitle: string = "Listing"
) {
  const isCar = type === ListingType.CAR;
  const isBike = type === ListingType.BIKE;
  const isPlate = type === ListingType.PLATE;

  let specificData: any = {};

  if (isCar) {
    specificData = {
      make: overrides.make || rnd(['Toyota', 'Nissan', 'Honda']),
      model: overrides.model || 'Camry',
      year: overrides.year || (2018 + Math.floor(Math.random() * 6)),
      mileage: Math.floor(Math.random() * 100000),
      bodyType: overrides.bodyType || 'Sedan',
      transmission: 'Automatic',
      fuelType: 'Petrol',
      color: rnd(['White', 'Black', 'Silver']),
      price: overrides.price || (5000 + Math.floor(Math.random() * 10000))
    };
  } else if (isBike) {
    specificData = {
      make: 'Harley Davidson',
      model: 'Sportster',
      year: 2020,
      bodyType: 'Cruiser',
      mileage: 2000,
      price: 3000 + Math.floor(Math.random() * 5000)
    };
  } else if (isPlate) {
    const num = Math.floor(Math.random() * 900000) + 100000;
    specificData = {
      plateNumber: num.toString(),
      plateCategory: 'Private',
      price: 1000 + Math.floor(Math.random() * 20000)
    };
  }

  const finalData = { ...specificData, ...overrides };

  await prisma.listing.create({
    data: {
      title: listingTitle,
      titleAr: `${listingTitle} (AR)`,
      description: 'Test listing description generated by seed script.',
      descriptionAr: 'وصف تجريبي تم إنشاؤه بواسطة السكربت.',
      type,
      status: ListingStatus.APPROVED,
      price: finalData.price,
      currency: 'BHD',
      ownerId: userId,
      city: 'Manama',
      contactPhone: '33333333',
      isFeatured: overrides.isFeatured || false,
      ...finalData,
      media: {
        create: [
          {
            url: isPlate 
              ? `https://dummyimage.com/600x400/000/fff&text=PLATE` 
              : `https://dummyimage.com/600x400/${Math.floor(Math.random()*16777215).toString(16)}/fff&text=${type}`,
            type: 'image',
            isPrimary: true
          }
        ]
      }
    }
  });
}

async function main() {
  console.log('🚀 Starting 10-Item Seeding...');
  const hashedPassword = await bcrypt.hash(DEFAULT_PASSWORD, SALT_ROUNDS);

  // 1. 10 SHOWROOMS (1 in each city region) + 1 Story each
  console.log('🏭 Seeding 10 Showrooms...');
  const showroomUsers: any[] = [];
  for (let i = 0; i < 10; i++) {
    const email = `showroom_new_${i}@test.com`;
    const city = CITIES[i % CITIES.length];
    
    const user = await prisma.user.upsert({
      where: { email },
      create: {
        email, password: hashedPassword, name: `Showroom ${city}`, role: UserRole.SHOWROOM,
        isApproved: true, isActive: true, phone: `399000${i}`,
        showroom: { create: { name: `Showroom ${city}`, city, isApproved: true } }
      },
      update: {},
      include: { showroom: true }
    });
    
    await ensurePackageExists(user);
    showroomUsers.push(user);
    // 1 Story
    await createStory(user.id);
  }

  // 2. 10 INDIVIDUALS/TRADERS -> 10 Listings + 10 Stories
  // We'll split 5 Individuals + 5 Traders
  console.log('👤 Seeding 10 Seller Accounts (5 Individual / 5 Trader)...');
  const sellerUsers: any[] = [];
  for (let i = 0; i < 10; i++) {
    const isTrader = i >= 5;
    const role = isTrader ? UserRole.TRADER : UserRole.INDIVIDUAL;
    const email = `seller_new_${i}@test.com`;
    
    const user = await prisma.user.upsert({
      where: { email },
      create: {
        email, password: hashedPassword, name: `${isTrader?'Trader':'Indiv'} ${i}`, role,
        isApproved: true, isActive: true, phone: `366000${i}`
      },
      update: {}
    });
    
    await ensurePackageExists(user);
    sellerUsers.push(user);

    // 1 Listing (Generic Car)
    await createListing(user.id, ListingType.CAR, {}, `Seller ${i} Car`);

    // 1 Story
    await createStory(user.id);
  }

  // Pick random users for the specialized car listings
  // We can use the showroom users or seller users. Let's mix them.
  const allSellers = [...showroomUsers, ...sellerUsers];

  // 3. 10 LUXURY CARS
  console.log('💎 Seeding 10 Luxury Cars...');
  for (let i = 0; i < 10; i++) {
    const owner = rnd(allSellers);
    const brand = LUXURY_BRANDS[i % LUXURY_BRANDS.length];
    await createListing(owner.id, ListingType.CAR, {
      make: brand,
      model: 'GT',
      price: 80000 + (i * 5000),
      bodyType: 'Coupe',
      year: 2023,
      isFeatured: true
    }, `${brand} Luxury`);
  }

  // 4. 10 CLASSIC CARS
  console.log('🕰️ Seeding 10 Classic Cars...');
  for (let i = 0; i < 10; i++) {
    const owner = rnd(allSellers);
    const brandModel = CLASSIC_BRANDS[i % CLASSIC_BRANDS.length]; 
    // split brand/model strictly for display, simplified
    await createListing(owner.id, ListingType.CAR, {
      make: 'Classic', // or real brand
      model: brandModel,
      price: 15000 + (i * 1000),
      year: 1960 + Math.floor(Math.random() * 20),
      bodyType: 'Classic',
      description: 'A beautiful classic car in mint condition.'
    }, `${brandModel} Classic`);
  }

  // 5. 10 MOTORCYCLES
  console.log('🏍️ Seeding 10 Motorcycles...');
  for (let i = 0; i < 10; i++) {
    const owner = rnd(allSellers);
    await createListing(owner.id, ListingType.BIKE, {}, `Motorcycle ${i + 1}`);
  }

  // 6. 10 PLATES
  console.log('🔢 Seeding 10 Plates...');
  for (let i = 0; i < 10; i++) {
    const owner = rnd(allSellers);
    await createListing(owner.id, ListingType.PLATE, {}, `Plate ${i + 1}`);
  }

  // 7. 10 CUSTOMS CLEARERS
  console.log('🛃 Seeding 10 Customs Clearers...');
  for (let i = 0; i < 10; i++) {
    const email = `clearer_new_${i}@test.com`;
    await prisma.user.upsert({
      where: { email },
      create: {
        email, password: hashedPassword, name: `Clearer ${i}`, role: UserRole.SERVICE_PROVIDER,
        isApproved: true, isActive: true, phone: `331100${i}`,
        serviceProvider: { 
          create: { 
            type: ServiceProviderType.CUSTOMS_CLEARER,
            name: `Clearance Service ${i}`, 
            city: CITIES[i % CITIES.length], 
            isApproved: true 
          } 
        }
      },
      update: {}
    });
  }

  // 8. 10 INSPECTION CENTERS
  console.log('🔍 Seeding 10 Inspection Centers...');
  for (let i = 0; i < 10; i++) {
    const email = `inspection_new_${i}@test.com`;
    await prisma.user.upsert({
      where: { email },
      create: {
        email, password: hashedPassword, name: `Inspection ${i}`, role: UserRole.SERVICE_PROVIDER,
        isApproved: true, isActive: true, phone: `332200${i}`,
        serviceProvider: { 
          create: { 
            type: ServiceProviderType.INSPECTION_CENTER,
            name: `CheckPoint ${i}`, 
            city: CITIES[i % CITIES.length], 
            isApproved: true 
          } 
        }
      },
      update: {}
    });
  }

  // 9. 10 POLISHING CENTERS
  console.log('✨ Seeding 10 Polishing Centers...');
  for (let i = 0; i < 10; i++) {
    const email = `polishing_new_${i}@test.com`;
    await prisma.user.upsert({
      where: { email },
      create: {
        email, password: hashedPassword, name: `Polishing ${i}`, role: UserRole.SERVICE_PROVIDER,
        isApproved: true, isActive: true, phone: `334400${i}`,
        serviceProvider: { 
          create: { 
            type: ServiceProviderType.POLISHING_CENTER,
            name: `Shiny Car ${i}`, 
            city: CITIES[i % CITIES.length], 
            isApproved: true 
          } 
        }
      },
      update: {}
    });
  }

  // 10. 10 OTHER CARS (General)
  console.log('🚗 Seeding 10 Other Cars...');
  for (let i = 0; i < 10; i++) {
    const owner = rnd(allSellers);
    await createListing(owner.id, ListingType.CAR, {
      make: 'Other',
      model: 'General Model',
      price: 3000
    }, `Daily Driver ${i+1}`);
  }

  console.log('✅ 10-Item Seeding Complete!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
